src/convex_hull_structs.cpp File Reference
#include `convex_hull_structs.h`
Functions
PolarPoint convertToPolar (Point p, Point origin)
int compareTheta (PolarPoint p, PolarPoint q)
int isEmpty (Node *root)
void push (Point p, Node **root)
Point pop (Node **root)
Point peek (Node **root)
void printStack (Node **root)
void printArray (PolarPoint p[], int n)
void printArray (Point p[], int n)
void swap (int i, int j, PolarPoint inp[])
void swap (int i, int j, Point inp[])
void swap (int i, int j, double inp[])
void swap_all (Point inp[])
void flipAll (Point inp[], Point out[], int size)
void flipSelf (Point inp[], int size)
Pairing sortPair (Pairing z)
Function Documentation
compareTheta()
int compareTheta (PolarPoint p, PolarPoint q)
Compares two PolarPoints based on which has lower theta
Parameters
p PolarPoint 1
q PolarPoint 2
Returns
0 for equal, -1 for p < q, 1 for p > q.
Definition at line 29 of file convex_hull_structs.cpp.
{
    // abs() returns a rounded value. fabs() is for doubles
    double diff = fabs(p.theta - q.theta);
    if(diff < 0.000000000001)
    {
        // Equal theta. Margin to account for floating point error
        return 0;
    }
    else if(p.theta > q.theta)
    {
        //greater
        return 1;
    }
    else
    {
        //lesser
        return -1;
    }
}
References PolarPoint::theta.
Referenced by removeThetaCollinear().
convertToPolar()
PolarPoint convertToPolar (Point p, Point origin)
Shifts the origin and then converts to Polar format
Parameters
p Point in cartesian that needs to be converted
origin Point in cartesian that is treated as origin
Returns
PolarPoint which is the conversion of the passed Point
Definition at line 10 of file convex_hull_structs.cpp.
{
    p.x -= origin.x;
    p.y -= origin.y;
    double r = sqrt(p.x*p.x + p.y*p.y);
    if(r == 0.0 || r == -0.0)
    {
        return PolarPoint(0.0,0.0,p.index);
    }
    double theta = atan(p.y/p.x);
    return PolarPoint(r,theta,p.index);
}
References Point::index, Point::x, and Point::y.
Referenced by getHull().
flipAll()
void flipAll (Point inp[], Point out[], int size)
Changes the sign of all elements in the inp array passed
Parameters
inp Point array
Returns
Point array with all elements having flipped sign compared to the input
Definition at line 191 of file convex_hull_structs.cpp.
{
    int i = 0;
    for(i=0; i < size; i++)
    {
        out[i].x = -1*inp[i].x;
        out[i].y = -1*inp[i].y;
        // out[i].index = inp[i].index;
    }
    return;
}
References Point::x, and Point::y.
Referenced by kpsHullCompute().
flipSelf()
void flipSelf (Point inp[], int size)
Definition at line 203 of file convex_hull_structs.cpp.
{
    int i = 0;
    for(i=0; i < size; i++)
    {
        inp[i].x = -inp[i].x;
        inp[i].y = -inp[i].y;
        // out[i].index = inp[i].index;
    }
    return;
}
References Point::x, and Point::y.
Referenced by kpsHullCompute().
isEmpty()
int isEmpty (Node * root)
Definition at line 54 of file convex_hull_structs.cpp.
{
    return !root;
}
Referenced by computeHull(), peek(), and pop().
peek()
Point peek (Node ** root)
Definition at line 79 of file convex_hull_structs.cpp.
{
    //Stack is never empty in our usage, but check is kept. TODO think of better return here
    if(isEmpty(*root))
    {
        return Point(-1.0,-1.0);
    }
    return (*root)->point;
}
References isEmpty().
Referenced by computeHull().
pop()
Point pop (Node ** root)
Definition at line 67 of file convex_hull_structs.cpp.
{
    //Stack is never empty in our usage, but check is kept. TODO think of better return here
    if(isEmpty(*root))
    {
        return Point(-1.0,-1.0);
    }
    Point p = (*root)->point;
    *root = (*root)->next;
    return p;
}
References isEmpty(), and Node::next.
Referenced by computeHull(), and main().
printArray() [1/2]
void printArray (Point p[], int n)
Prints out all the elements in the array passed
Parameters
p Array to be printed
n Length of the array
Definition at line 121 of file convex_hull_structs.cpp.
{
    for (int i = 0; i < n; i++) {
        printf("%f,%f\n",p[i].x,p[i].y);
    }
}
printArray() [2/2]
void printArray (PolarPoint p[], int n)
Prints out all the elements in the array passed
Parameters
p Array to be printed
n Length of the array
Definition at line 109 of file convex_hull_structs.cpp.
{
    for (int i = 0; i < n; i++) {
        std::cout << p[i].r << ',' << p[i].theta << std::endl;
    }
}
References PolarPoint::r, and PolarPoint::theta.
printStack()
void printStack (Node ** root)
Definition at line 89 of file convex_hull_structs.cpp.
{
    Node* temp = *root;
    while(temp!=NULL)
    {
        printf("(%f,%f)\n",temp->point.x,temp->point.y);
        temp = temp->next;
    }
    printf("\n");
}
References Node::next, Node::point, Point::x, and Point::y.
push()
void push (Point p, Node ** root)
Definition at line 59 of file convex_hull_structs.cpp.
{
    Node* temp = (Node*) malloc(sizeof(Node));
    temp->point = p;
    temp->next = *root;
    *root = temp;
}
References Node::next, and Node::point.
Referenced by computeHull().
sortPair()
Pairing sortPair (Pairing z)
Definition at line 215 of file convex_hull_structs.cpp.
{
    if(z.p.x > z.q.x)
    {
        // printf("Reached here\n");
        Point temp;
        temp.x = z.p.x;
        temp.y = z.p.y;
        z.p.x = z.q.x;
        z.p.y = z.q.y;
        z.q.x = temp.x;
        z.q.y = temp.y;
    }
    return z;
}
References Pairing::p, Pairing::q, Point::x, and Point::y.
Referenced by bridgeFinder().
swap() [1/3]
void swap (int i, int j, double inp[])
Swaps the elements i and j in the inp array passed
Parameters
i integer index
j integer index
inp Point array
Definition at line 162 of file convex_hull_structs.cpp.
{
    double temp = inp[i];
    inp[i] = inp[j];
    inp[j] = temp;
    return;
}
swap() [2/3]
void swap (int i, int j, Point inp[])
Swaps the elements i and j in the inp array passed
Parameters
i integer index
j integer index
inp Point array
Definition at line 148 of file convex_hull_structs.cpp.
{
    Point temp = inp[i];
    inp[i] = inp[j];
    inp[j] = temp;
    return;
}
swap() [3/3]
void swap (int i, int j, PolarPoint inp[])
Swaps the elements i and j in the inp array passed
Parameters
i integer index
j integer index
inp PolarPoint array
Definition at line 134 of file convex_hull_structs.cpp.
{
    PolarPoint temp = inp[i];
    inp[i] = inp[j];
    inp[j] = temp;
    return;
}
Referenced by getHull(), partitioning(), sortPoints(), and swap_all().
swap_all()
void swap_all (Point inp[])
Reverses the elements in the inp array passed
Parameters
inp Point array
Definition at line 174 of file convex_hull_structs.cpp.
{
    int size = *(&inp + 1) - inp;
    int i = 0;
    Point temp;
    for(i=0; i< size/2; i++)
    {
        swap(i, size-1-i, inp);
    }
    return;
}
References swap().