include/kirkpatrickseidel.h File Reference
#include <iostream>
#include <stdlib.h>
#include `convex_hull_structs.h`
Functions
int kpsHullCompute (Point input[], Point result[], int N)
void upperHull (Point input[], Point result[], int N)
void connect (Point minxIndex, Point maxIndex, Point upperPoints[], Point result[], int lesserN)
Pairing bridgeFinder (Point upperPoints[], int upperLine, int size)
void safeInitialization (int arr[], int size)
void safeInitialization (double arr[], int size)
void copyInitialization (Point target[], Point base[], int size)
void copyInitialization (double target[], double base[], int size)
int kpsGetLeftMostPoint (Point p[], int N)
int kpsGetRightMostPoint (Point p[], int N)
Variables
int pointTracker
Function Documentation
bridgeFinder()
Pairing bridgeFinder (Point upperPoints[], int upperLine, int size)
Definition at line 180 of file kirkpatrickseidel.cpp.
{
    Point candidates[size];
    int update = 0;
    if (size == 2)
    {
        Pairing tempPair = Pairing(upperPoints[0], upperPoints[1]);
        // cout<<"Sorting Start"<<endl;
        // cout<<tempPair.p.x<<endl;
        // cout<<tempPair.q.x;
        tempPair = sortPair(tempPair);
        // cout<<tempPair.p.x<<endl;
        // cout<<"Sorting Done"<<endl;
        return tempPair;
    }
    int numPairs = 0;
    if (size%2 == 1) // Add the left out element to pairings
    {
        candidates[update] = upperPoints[size-1];
        update++;
        numPairs = (size-1)/2;
    }
    else
    {
        numPairs = size/2;
    }
    int i = 0;
    Pairing pairs[numPairs];
    for(i = 0; i < size-1; i+=2)
    {
        pairs[i/2] = Pairing(upperPoints[i], upperPoints[i+1]);
        // cout<<"Points "<<pairs[i/2].p.x<<" "<<pairs[i/2].p.y<<" "<<pairs[i/2].q.x<<" "<<pairs[i/2].q.y<<endl;
        pairs[i/2] = sortPair(pairs[i/2]);
        // cout<<"Points "<<pairs[i/2].p.x<<" "<<pairs[i/2].p.y<<" "<<pairs[i/2].q.x<<" "<<pairs[i/2].q.y<<endl;
    }
    // cout<<endl;
    // cout<<"Size is"<<size<<endl;
    // cout<<"NumPairs is"<<numPairs<<endl;
    // cout<<endl;
    double slopes[numPairs];
    safeInitialization(slopes, numPairs);
    int slopeUpdate = 0;
    for(i = 0; i < numPairs; i+=1)
    {
        Pairing temp = pairs[i];
        if(temp.p.x == temp.q.x)
        {
            pairs[i/2].redact = 1; // Remove from consideration
            if(temp.p.y > temp.q.y)
            {
                candidates[update] = temp.p;
                update++;
            }
            else
            {
                candidates[update] = temp.q;
                update++;
            }
        }
        else
        {
            // cout<<"Point's slopes "<<pairs[i].p.x<<" "<<pairs[i].p.y<<" "<<pairs[i].q.x<<" "<<pairs[i].q.y<<endl;
            slopes[slopeUpdate] = ((temp.p.y - temp.q.y) / (temp.p.x - temp.q.x));
            // cout<<slopes[slopeUpdate]<<endl;
            slopeUpdate++;
        }
    }
    // cout<<"SlopeUpdate is"<<slopeUpdate<<endl;
    // cout<<slopes[0]<<" "<<slopes[1]<<endl;
    int medianIndex;
    if(slopeUpdate%2 == 0)
    {
        medianIndex = slopeUpdate/2;
    }
    else
    {
        medianIndex = slopeUpdate - 1 /2;
    }
    double temp[numPairs];
    copyInitialization(temp, slopes, slopeUpdate);
    // cout<<"Slopeupdate is"<<slopeUpdate<<endl;
    double medianSlope = slopes[quickselect(medianIndex, 0, slopeUpdate -1, temp)];
    // cout<<"Slopeupdate is"<<slopeUpdate<<endl;
    // cout<< "MS"<<medianSlope<<" "<<slopes[0]<<endl;
    Pairing small[slopeUpdate], equal[slopeUpdate], large[slopeUpdate];
    int smallCount=0, equalCount=0, largeCount=0;
    int skip = 0;
    for(i=0; i<numPairs;i++)
    {
        if(pairs[i].redact == 1)
        {
            skip++;
        }
        else
        {
            // Assign to small, equal and large
            if(slopes[i - skip] < medianSlope)
            {
                small[smallCount++] = pairs[i];
            }
            else if(slopes[i-skip] == medianSlope)
            {
                equal[equalCount++] = pairs[i];
            }
            else
            {
                large[largeCount++] = pairs[i];
            }
        }
    }
    // cout<<smallCount<<" "<<equalCount<<" "<<largeCount<<endl;
    // Get max slope
    double maxSlope = upperPoints[0].y - medianSlope * upperPoints[0].x;
    Point leftLargeSlopePoint = upperPoints[0];
    Point rightLargeSlopePoint = upperPoints[0];
    for(i=0; i<size; i++)
    {
        double newSlope = upperPoints[i].y - medianSlope * upperPoints[i].x;
        if (newSlope > maxSlope)
        {
            maxSlope = newSlope;
            leftLargeSlopePoint = upperPoints[i];
            rightLargeSlopePoint = upperPoints[i];
        }
        else if(newSlope == maxSlope)
        {
            if(upperPoints[i].x < leftLargeSlopePoint.x)
            {
                leftLargeSlopePoint = upperPoints[i];
            }
            if(upperPoints[i].x > rightLargeSlopePoint.x)
            {
                rightLargeSlopePoint = upperPoints[i];
            }
        }
    }
    // cout<<maxSlope<<endl;
    // cout<<leftLargeSlopePoint.x<<" "<<leftLargeSlopePoint.y<<endl;
    // cout<<rightLargeSlopePoint.x<<" "<<rightLargeSlopePoint.y<<endl;
    if(leftLargeSlopePoint.x <= upperLine && rightLargeSlopePoint.x > upperLine)
    {
        Pairing tempPair = Pairing(leftLargeSlopePoint, rightLargeSlopePoint);
        tempPair = sortPair(tempPair);
        return tempPair;
    }
    if(rightLargeSlopePoint.x <= upperLine)
    {
        // Small
        for(i=0; i< smallCount;i++)
        {
            candidates[update++] = small[i].p;
            candidates[update++] = small[i].q;
        }
        // Medium
        for(i = 0; i < equalCount; i++)
        {
            candidates[update++] = equal[i].q;
        }
        //Large
        for(i = 0; i < largeCount; i++)
        {
            candidates[update++] = large[i].q;
        }
    }
    if(leftLargeSlopePoint.x > upperLine)
    {
        // Small
        for(i=0; i< smallCount; i++)
        {
            candidates[update++] = small[i].p;
        }
        // Medium
        for(i = 0; i < equalCount; i++)
        {
            candidates[update++] = equal[i].p;
        }
        //Large
        for(i = 0; i < largeCount; i++)
        {
            candidates[update++] = large[i].p;
            candidates[update++] = large[i].q;
        }
    }
    // cout<<update<<endl;
    // cout<<upperLine<<endl;
    return bridgeFinder(candidates, upperLine, update);
}
References bridgeFinder(), copyInitialization(), Pairing::p, Pairing::q, quickselect(), Pairing::redact, safeInitialization(), sortPair(), Point::x, and Point::y.
Referenced by bridgeFinder(), and connect().
connect()
void connect (Point minxIndex, Point maxIndex, Point upperPoints[], Point result[], int lesserN)
Definition at line 376 of file kirkpatrickseidel.cpp.
{
    int i = 0;
    if (minx.x == maxx.x && minx.y == maxx.y)
    {
        result[pointTracker] = minx;
        pointTracker++;
        return;
    }
    Point temp[lesserN];
    copyInitialization(temp, upperPoints, lesserN);
    Point max_left = temp[quickselect((lesserN)/2, 0, lesserN - 1, temp)];
    // cout<<"Max L "<<max_left.x<<" "<< max_left.y<<endl;
    copyInitialization(temp, upperPoints, lesserN);
    Point min_right = temp[quickselect(lesserN/2 + 1, 0, lesserN - 1, temp)];
    // cout<<"Min R "<<min_right.x<<" "<<min_right.y<<endl;
    Pairing leftright = bridgeFinder(upperPoints, (max_left.x + min_right.x)/2, lesserN);
    // cout<<"Smaller left"<<leftright.p.x<<" "<<leftright.p.y<<endl;
    // cout<<"Greater right"<<leftright.q.x<<" "<<leftright.q.y<<endl;
    // cout<<endl;
    Point leftPoints[lesserN];
    int leftPointsIndex = 0;
    for(i=0; i < lesserN; i++)
    {
        if((upperPoints[i].x < leftright.p.x) || (upperPoints[i].x == leftright.p.x && upperPoints[i].y == leftright.p.y))
        {
            leftPoints[leftPointsIndex++] = upperPoints[i];
        }
    }
    Point rightPoints[lesserN];
    int rightPointsIndex = 0;
    for(i=0; i < lesserN; i++)
    {
        if((upperPoints[i].x > leftright.q.x) || (upperPoints[i].x == leftright.q.x && upperPoints[i].y == leftright.q.y))
        {
            rightPoints[rightPointsIndex++] = upperPoints[i];
        }
    }
    // int leftIndex;
    // for(i=0; i < leftPointsIndex; i++)
    // {
    // if(leftPoints[i].x == leftright.p.x && leftPoints[i].y == leftright.p.y)
    // {
    // leftIndex = i;
    // }
    // }
    // int rightIndex;
    // for(i=0; i < rightPointsIndex; i++)
    // {
    // if((rightPoints[i].x == leftright.q.x && rightPoints[i].y == leftright.q.y))
    // {
    // rightIndex = i;
    // }
    // }
    // cout<<"**Left**"<<leftPointsIndex<<endl;
    connect(minx, leftright.p, leftPoints, result, leftPointsIndex);
    // cout<<endl;
    // cout<<"**Right**"<<rightPointsIndex<<endl;
    // cout<<"R is"<<leftright.q.x<<" "<<leftright.q.y<<endl;
    // cout<<"Max is"<<maxx.x<<" "<<maxx.y<<endl;
    connect(leftright.q, maxx, rightPoints, result, rightPointsIndex);
}
References bridgeFinder(), connect(), copyInitialization(), Pairing::p, pointTracker, Pairing::q, quickselect(), Point::x, and Point::y.
Referenced by connect(), and upperHull().
copyInitialization() [1/2]
void copyInitialization (double target[], double base[], int size)
Definition at line 36 of file kirkpatrickseidel.cpp.
{
    int i = 0;
    for(i = 0; i < size; i++)
    {
        target[i] = base[i];
    }
}
copyInitialization() [2/2]
void copyInitialization (Point target[], Point base[], int size)
Definition at line 27 of file kirkpatrickseidel.cpp.
{
    int i = 0;
    for(i = 0; i < size; i++)
    {
        target[i] = base[i];
    }
}
Referenced by bridgeFinder(), connect(), and kpsHullCompute().
kpsGetLeftMostPoint()
int kpsGetLeftMostPoint (Point p[], int N)
Definition at line 45 of file kirkpatrickseidel.cpp.
{
  int index_ref = 0, i = 0;
  for (i = 1; i < N; i++)
  {
    if(p[i].x < p[index_ref].x)
    {
      index_ref = i;
    }
    else if(p[i].x == p[index_ref].x)
    {
      if(p[i].y > p[index_ref].y)
      {
        index_ref = i;
      }
    }
  }
  return index_ref;
}
Referenced by upperHull().
kpsGetRightMostPoint()
int kpsGetRightMostPoint (Point p[], int N)
Definition at line 65 of file kirkpatrickseidel.cpp.
{
  int index_ref = 0, i = 0;
  for (i = 1; i < N; i++)
  {
    if(p[i].x > p[index_ref].x)
    {
      index_ref = i;
    }
    else if(p[i].x == p[index_ref].x)
    {
      if(p[i].y > p[index_ref].y)
      {
        index_ref = i;
      }
    }
  }
  return index_ref;
}
Referenced by upperHull().
kpsHullCompute()
int kpsHullCompute (Point input[], Point result[], int N)
Definition at line 466 of file kirkpatrickseidel.cpp.
{
    int i = 0;
    Point upper[N];
    copyInitialization(upper, input, N);
    Point lower[N];
    flipAll(input, lower, N);
    // cout<<"wababa"<<lower[0].x<<endl;
    Point resultUpper[N];
    int resultUpperIndex = 0;
    Point resultLower[N];
    int resultLowerIndex = 0;
    upperHull(upper, resultUpper, N);
    resultUpperIndex = pointTracker;
    pointTracker = 0;
    // cout<<"wababa"<<lower[0].x<<endl;
    upperHull(lower, resultLower, N);
    resultLowerIndex = pointTracker;
    // cout<<resultLowerIndex<<endl;
    // cout<<resultUpper[0].x<<endl;
    flipSelf(resultLower, resultLowerIndex);
    // cout<<resultUpper[0].x<<endl;
    //Merging
    if(resultLower[resultLowerIndex-1].x == resultUpper[0].x && resultLower[resultLowerIndex-1].y == resultUpper[0].y)
    {
        resultLowerIndex -= 1;
    }
    if(resultLower[0].x == resultUpper[resultUpperIndex-1].x && resultLower[0].y == resultUpper[resultUpperIndex-1].y)
    {
        resultUpperIndex -= 1;
    }
    for(i = 0;i < resultUpperIndex;i++)
    {
        result[i] = resultUpper[i];
    }
    for(i = resultUpperIndex; i<resultUpperIndex + resultLowerIndex;i++)
    {
        result[i] = resultLower[i-resultUpperIndex];
    }
    // for(i = 0; i < resultLowerIndex; i++)
    // {
    // cout<<resultLower[i].x<<","<<resultLower[i].y<<endl;
    // }
    return resultUpperIndex + resultLowerIndex;
}
References copyInitialization(), flipAll(), flipSelf(), pointTracker, and upperHull().
Referenced by main().
safeInitialization() [1/2]
void safeInitialization (double arr[], int size)
Definition at line 17 of file kirkpatrickseidel.cpp.
{
    int i = 0;
    for(i = 0; i < size; i++)
    {
        arr[i] = -1;
    }
    return;
}
safeInitialization() [2/2]
void safeInitialization (int arr[], int size)
Definition at line 7 of file kirkpatrickseidel.cpp.
{
    int i = 0;
    for(i = 0; i < size; i++)
    {
        arr[i] = -1;
    }
    return;
}
Referenced by bridgeFinder().
upperHull()
void upperHull (Point input[], Point result[], int N)
Definition at line 439 of file kirkpatrickseidel.cpp.
{
    // cout<<kpsGetLeftMostPoint(input, N)<<endl;
    // cout<<kpsGetRightMostPoint(input, N)<<endl;
    int minxIndex = kpsGetLeftMostPoint(input, N);
    int maxxIndex = kpsGetRightMostPoint(input, N);
    int i = 0, lesserN = 0, j = 0;
    for(i = 0; i < N; i++)
    {
        if((input[i].x > input[minxIndex].x && input[i].x < input[maxxIndex].x) || i == minxIndex || i == maxxIndex)
        {
            lesserN++;
        }
    }
    Point upperPoints[lesserN]; // excluding the possible vertical edges of xmin and xmax
    for(i = 0; i < N; i++)
    {
        if((input[i].x > input[minxIndex].x && input[i].x < input[maxxIndex].x) || i == minxIndex || i == maxxIndex)
        {
            upperPoints[j++] = input[i];
        }
    }
    // printArray(upperPoints, lesserN);
    connect(input[minxIndex], input[maxxIndex], upperPoints, result, lesserN);
    return;
}
References connect(), kpsGetLeftMostPoint(), and kpsGetRightMostPoint().
Referenced by kpsHullCompute().
Variable Documentation
pointTracker
int pointTracker
Definition at line 5 of file kirkpatrickseidel.cpp.
Referenced by connect(), and kpsHullCompute().